name: vectordb-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
      - requests
      - tabulate
      - chromadb
      - sentence-transformers
      - numpy
      - torch
      - transformers
      - tqdm
      - elasticsearch
      - pyyaml
      - python-dotenv
